title: The Hackerspace Blueprint
description: A guide on how to run a hackerspace
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
basename: /hackerspace-blueprint-website
github:
  epub_url: https://github.com/0x20/hackerspace-blueprint/releases/latest/download/hackerspace-blueprint.epub
  pdf_url: https://github.com/0x20/hackerspace-blueprint/releases/latest/download/hackerspace-blueprint.pdf
  is_project_page: True
  repository_url: https://github.com/0x20/hackerspace-blueprint


podcast_url: https//hackerspace.design/hackerspacedesign
podcast_album_art: /assets/images/download-button.png
podcast_title: Hackerspace Design
podcast_owner: Merlijn Sebrechts
podcast_email: merlijn.sebrechts@gmail.com
podcast_category: Technology
podcast_subcategory_one: Software How-To
podcast_subcategory_two: Gadgets
podcast_explicit: "no"
podcast_author: Merlijn Sebrechts
podcast_description: Productivity stories from the trenches. What works and what I'll never do again. Hosted by Joe Buhlig.
podcast_summary: Joe Buhlig walks you through real life story and then breaks down the productivity tools and techniques used. It's a great way to learn how to implement the tips and tricks that you see across the web. Productivity stories from the trenches. What works and what to never try.
podcast_subtitle: Productivity stories from the trenches. What works and what I'll never do again. Hosted by Joe Buhlig.
